### ISSUE TITLE
Support managing Scholar embargoes and viewing embargoed objects with owner proxy

### ISSUE THREAD

**Issue by axfelix** [discoverygarden/islandora_access_override#8]
Just noticed that Scholar embargoes don't seem to be one of the permissions that can be proxied by this module, which is a gap for us.

**Comment by willtp87** [comment]
I'm sorry but overriding scholar embargoes would be firmly outside the capabilities of this module. This module works entirely within the Drupal permissions system while scholar's embargoes are enforced by Fedora itself. We can't override the datastore denying access at the application level. One could imagine a system that enables user swapping under custom circumstances but it would require extensive hardening.
