### ISSUE TITLE
500 error when viewing orphaned objects using Islandora Collection Permissions

### ISSUE THREAD

**Issue by bondjimbond** [discoverygarden/islandora_access_override#9]
When attempting to view an orphaned object (object with a parent defined in RELS-EXT, but parent doesn't actually exist), you get a 500 error and the following in the logs:

> Notice: Trying to get property of non-object in IslandoraCollectionPermissionsHandler->getRelatedPids() (line 197 of /var/www/html/drupal7/sites/all/modules/islandora_access_override/modules/islandora_collection_permissions/includes/handler.class.inc).

Turn off Islandora Collection Permissions, and the object can be accessed. Turn it on again, and the 500 error appears.

**Comment by qadan** [comment]
Thanks for this! I'm gonna pop this into the queue of things to get fixed when I get back in on Monday. Looks like a cut-and-dry case of just adding the `NULL`/`FALSE` check after `islandora_object_load()`

**Comment by mghughes** [comment]
#10 has been merged now - closing this issue
